

---
 - name: Install Apache and Upload Web page
   hosts: all
   become: yes

   vars:
    source_file: ./Web_Site/index.html
    destin_file: /var/www/html

   tasks:
    - name: Check Linux
      debug: var=ansible_os_family
      
    - block: # Block for Redhat
 
       - name: Install Apache Web Server
         yum: name=apache2 state=latest
        
      
       - name: Start Webserver
         service: name=apache2 state=started enabled=yes
        
      when: ansible_os_family=="RedHat"

    - block: #Block for Debian
 
       - name: Intsall htop for debian
         apt: name=htop state=latest
        
      
       - name: Start Webserver
         service: name=apache2 state=started enabled=yes
     
       
        
    
    - name: Copy my Web site
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache




   handlers:
     - name: Restart Apache for Debian
       service: name=apache2 state=restarted
     

