
---
 - name: Install appache
   hosts: all
   become: yes

   tasks:
   - name: Install Apache WebServer
     yum:  name=apache2 state=latest
  
   - name: Start Apache and Enable 
     service: name=apache2 state=started enabled=yes
    
